language: ruby
rvm:
- 2.4.5
before_install:
- gem update --system
- gem install bundler
before_script:
- psql -c 'create database travis_ci_test;' -U postgres
env:
  global:
    secure: GvLhlaCpn4M2P9HKY48SYYntcd5cyDC4EQIiy0BqtGIOCXJTfB4FTg7IdOEGDjOXsQBkCFWgM+nA3gUWSdEbVBi0BTXdkK9Le7bxMDhyi/fxDIE8SsHBpug/VNiJavbWQ6vZoZS8N00+Kn3SvmEqb+Amw+GPCta1xGaXlbud0/IlA0aMB9eFeaoLTuDHtG5Cg1dn6Su0RaS+bowLvEXCippB/ntTx/x3z4nXXRAL2Zxy2jeIZK27GgpRPpTxWBon+j3UPxk88p0kM/YFmI65KWFwD5dK/CxWg7TQ6HNg4IEuQgLhy51LcBVqSP//n4v0tIEgWSgqPKHpKstuKvnpOOegeY3y0WVF08DW95NdFrFtDzKjq3c/WZioHooIUDjmEfURdIAmah2826UfxJKLprSfu92w4757tTBRI1DUifKQH6SlVCPCeuxgs4ozOxblQ1H67FSxTqyD8WxWdEQ9WNPx/HFbpXCABFnO9XdktwQRX2mcRgBKUwoymMC8XCOUJaOMbwtygDfOrtJjWarjeQnV5aB4XPdFfTijo7DEAGmvAuOssmO/mkHPhGVyagmIFLV/3LKYdldUeIab6vAk5PQzJnsHtS2NXJQen7PaNPGxtQDTY1aFlgPZpNoK1PaR+8cTMM2Fci9FjXGEmsVHBwDCd3KHffq4kZwixNcixkY=
